"""LLM client abstraction with mock and real implementations."""

import os
from abc import ABC, abstractmethod
from typing import Any


class BaseLLMClient(ABC):
    """Base LLM client interface."""

    @abstractmethod
    async def generate(self, prompt: str, **kwargs) -> str:
        """Generate text from prompt."""
        pass

    @abstractmethod
    async def extract_entities(self, text: str, entity_types: list[str]) -> list[dict[str, Any]]:
        """Extract entities from text."""
        pass

    @abstractmethod
    async def generate_explanation(
        self,
        findings: dict[str, Any],
        evidence: dict[str, Any],
        template: str | None = None,
    ) -> str:
        """Generate clinical explanation."""
        pass


class MockLLMClient(BaseLLMClient):
    """Mock LLM client for development and testing."""

    async def generate(self, prompt: str, **kwargs) -> str:
        """Generate mock response."""
        return f"[MOCK LLM RESPONSE] Prompt received ({len(prompt)} chars)"

    async def extract_entities(self, text: str, entity_types: list[str]) -> list[dict[str, Any]]:
        """Extract mock entities from text using simple pattern matching."""
        entities = []

        # Simple keyword-based extraction for common clinical terms
        keywords = {
            "DIAGNOSIS": [
                "adenocarcinoma", "carcinoma", "lung cancer", "nsclc",
                "non-small cell", "squamous cell",
            ],
            "MUTATION": ["egfr", "kras", "tp53", "alk", "ros1", "braf"],
            "PATTERN": [
                "lepidic", "acinar", "papillary", "micropapillary", "solid",
            ],
            "STAGE": ["stage i", "stage ii", "stage iii", "stage iv", "t1", "t2", "t3", "t4"],
        }

        text_lower = text.lower()

        for entity_type, terms in keywords.items():
            if entity_type in entity_types or not entity_types:
                for term in terms:
                    start = 0
                    while True:
                        idx = text_lower.find(term, start)
                        if idx == -1:
                            break
                        entities.append({
                            "text": text[idx:idx + len(term)],
                            "type": entity_type,
                            "start": idx,
                            "end": idx + len(term),
                            "confidence": 0.85,
                        })
                        start = idx + 1

        return entities

    async def generate_explanation(
        self,
        findings: dict[str, Any],
        evidence: dict[str, Any],
        template: str | None = None,
    ) -> str:
        """Generate mock clinical explanation."""
        patterns = findings.get("patterns", [])
        mutations = findings.get("mutations", [])

        explanation = """
## Clinical Findings Summary

### Histological Patterns
"""
        for p in patterns:
            status = "detected" if p.get("score", 0) > 0.5 else "not detected"
            explanation += f"- **{p.get('pattern', 'Unknown')}**: {status} (score: {p.get('score', 0):.2f})\n"

        explanation += """
### Genetic Mutation Analysis
"""
        for m in mutations:
            explanation += f"- **{m.get('mutation', 'Unknown')}**: {m.get('status', 'INCONCLUSIVE')} (score: {m.get('score', 0):.2f})\n"

        explanation += """
### Evidence Sources
- Image analysis results
- EHR clinical notes (if available)
- Ontology mappings (NCIt/MONDO/SO)

### Limitations
- This is an AI-assisted analysis and should not be used as a definitive diagnosis.
- All findings should be confirmed by a qualified pathologist.
- Model version and thresholds may affect results.

---
*Generated by DERCAS-ONCO-XAI (Mock Mode)*
"""
        return explanation


class OpenAILLMClient(BaseLLMClient):
    """OpenAI-based LLM client."""

    def __init__(self, api_key: str, model: str = "gpt-4"):
        self.api_key = api_key
        self.model = model

    async def generate(self, prompt: str, **kwargs) -> str:
        """Generate using OpenAI."""
        try:
            from langchain_openai import ChatOpenAI

            llm = ChatOpenAI(api_key=self.api_key, model=self.model)
            response = await llm.ainvoke(prompt)
            return response.content
        except ImportError:
            raise RuntimeError("langchain-openai not installed")

    async def extract_entities(self, text: str, entity_types: list[str]) -> list[dict[str, Any]]:
        """Extract entities using OpenAI."""
        prompt = f"""Extract clinical entities from the following text.
Entity types to extract: {', '.join(entity_types)}

Text:
{text}

Return a JSON array of entities with format:
[{{"text": "...", "type": "...", "start": N, "end": N, "confidence": 0.X}}]
"""
        response = await self.generate(prompt)
        # Parse JSON from response
        import json
        try:
            return json.loads(response)
        except json.JSONDecodeError:
            return []

    async def generate_explanation(
        self,
        findings: dict[str, Any],
        evidence: dict[str, Any],
        template: str | None = None,
    ) -> str:
        """Generate explanation using OpenAI."""
        prompt = f"""Generate a clinical explanation report based on the following findings.

Findings:
{findings}

Evidence:
{evidence}

Requirements:
1. Never make definitive diagnostic statements
2. Always include confidence scores and thresholds
3. Include a "Limitations" section
4. Reference model versions and ontology versions
5. Use professional medical language
"""
        return await self.generate(prompt)


def get_llm_client(
    provider: str | None = None,
    api_key: str | None = None,
) -> BaseLLMClient:
    """Get LLM client based on configuration."""
    provider = provider or os.getenv("LLM_PROVIDER", "mock")

    if provider == "mock":
        return MockLLMClient()
    elif provider == "openai":
        key = api_key or os.getenv("OPENAI_API_KEY")
        if not key:
            raise ValueError("OPENAI_API_KEY required for OpenAI provider")
        return OpenAILLMClient(api_key=key)
    else:
        # Default to mock
        return MockLLMClient()
