"""Pydantic models for Oncology XAI."""

from oncology_common.models.base import (
    BaseModel,
    BaseResponse,
    PaginatedResponse,
    ErrorResponse,
    ErrorDetail,
)
from oncology_common.models.entities import (
    Patient,
    PatientCreate,
    Case,
    CaseCreate,
    CaseStatus,
    Image,
    ImageCreate,
    ImageFormat,
    ResultBundle,
    PatternResult,
    GeneticResult,
    MutationStatus,
    PatternType,
    MutationType,
    EHRDocument,
    EHREntity,
    EHRMapping,
    GraphSnapshot,
    ExplanationReport,
    OntologyVersion,
    UpdateProposal,
    ProposalStatus,
    AuditEvent,
)

__all__ = [
    "BaseModel",
    "BaseResponse",
    "PaginatedResponse",
    "ErrorResponse",
    "ErrorDetail",
    "Patient",
    "PatientCreate",
    "Case",
    "CaseCreate",
    "CaseStatus",
    "Image",
    "ImageCreate",
    "ImageFormat",
    "ResultBundle",
    "PatternResult",
    "GeneticResult",
    "MutationStatus",
    "PatternType",
    "MutationType",
    "EHRDocument",
    "EHREntity",
    "EHRMapping",
    "GraphSnapshot",
    "ExplanationReport",
    "OntologyVersion",
    "UpdateProposal",
    "ProposalStatus",
    "AuditEvent",
]
