[lint]
select = ["E", "F", "W", "I", "B", "C4", "UP"]
ignore = ["E501", "B008", "C901"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"**/tests/**" = ["B011"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
